name: tsp_dart_lnurl
description: A Dart implementation of lnurl to decode bech32 lnurl strings.
version: 0.2.1
homepage: https://github.com/thespielplatz/dart_lnurl

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  bech32: ^0.2.1
  http: ^1.3.0

dev_dependencies:
  test: ^1.24.4

flutter:
